---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      image: darron/ubuntu:12.04
      platform: ubuntu

suites:
  - name: default
    run_list:
      - recipe[consul::default]
    attributes:
